#pragma config(Motor,  port1,   craneMotor, 		 tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,   rightMotor,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,   leftMotor,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,   leftClawMotor,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,   rightClawMotor,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,  armMotor,        tmotorVex393_HBridge, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                              - Dual Joystick Control with 4 Motors -                               *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]                [Type]                [Description]                   *|
|*    Motor Port 2        rightMotor            VEX 3-wire module     Right side motor                *|
|*    Motor Port 3        leghtMotor            VEX 3-wire module     Left side motor                 *|
|*    Motor Port 4        clawMotor			        VEX 3-wire module     Left side motor                 *|
|*    Motor Port 5        clawMotor             VEX 3-wire module     Left side motor                 *|
\*----------------------------------------------------------------------------------------------------*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main(){
		while(true) {
			  /* See http://www.robotc.net/wikiarchive/Data_Types for
			   * a list of variables */


				/* Handles movement and turning.
				* Left side speed  = Left joystick vertical motion
				* Right side speed = Right joystick vertical motion */
				motor[leftMotor] = -vexRT[Ch3];
				motor[rightMotor] = -vexRT[Ch2];

				/* Crane */
				if(vexRT[Btn5U] == 1) {
						motor[craneMotor] = 127;
				}
				else if(vexRT[Btn5D] == 1) {
						motor[craneMotor] = -127;
				}
				else {
						motor[craneMotor] = 0;
				}

				/* Arm motor */
				if(vexRT[Btn6U] == 1) {
						motor[armMotor] = 127;
				}
				else if(vexRT[Btn6D] == 1) {
						motor[armMotor] = -127;
				}
				else {
						motor[armMotor] = 0;
				}

				// Claw Controls
				if(vexRT[Btn7L] == 1){
						motor[leftClawMotor] = 127;
				}
				if(vexRT[Btn7R] == 1){
						motor[leftClawMotor] = -127;
				}
				if(vexRT[Btn8L] == 1){
						motor[rightClawMotor] = 127;
				}
				if(vexRT[Btn8R] == 1){
						motor[rightClawMotor] = -127;
				}
		}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
