using namespace vex;
vex::brain Brain;
vex::motor Motor04dr (vex::PORT1, vex::gearSetting::ratio18_1,true);
vex::motor Motor16dr (vex::PORT2, vex::gearSetting::ratio18_1,true);
vex::motor Motor01dl (vex::PORT9, vex::gearSetting::ratio18_1,false);
vex::motor Motor11dl (vex::PORT10, vex::gearSetting::ratio18_1,false);
vex::motor Motor05sp (vex::PORT11, vex::gearSetting::ratio6_1,false);
vex::motor Motor02dr (vex::PORT12, vex::gearSetting::ratio18_1,true);
vex::motor Motor03dl (vex::PORT20, vex::gearSetting::ratio18_1,false);
vex::controller Controller1;
vex::competition Competition;